// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	aggregates "github.com/westcottian/vwap-calculation-engine/internal/aggregates"

	testing "testing"
)

// VWAPPublisher is an autogenerated mock type for the VWAPPublisher type
type VWAPPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: aggregate
func (_m *VWAPPublisher) Publish(aggregate aggregates.VWAPAggregate) {
	_m.Called(aggregate)
}

// NewVWAPPublisher creates a new instance of VWAPPublisher. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewVWAPPublisher(t testing.TB) *VWAPPublisher {
	mock := &VWAPPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
